[project]
name = "chatbot-with-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.1.1",
    "fastapi>=0.118.2",
    "ipykernel>=7.0.1",
    "pandas>=2.3.3",
    "pydantic[email]>=2.12.0",
    "pydantic-settings>=2.11.0",
    "sentence-transformers>=5.1.1",
    "uvicorn>=0.37.0",
    "python-jose[cryptography]>=3.3.0",
    "python-multipart>=0.0.6",
    "jwt>=1.4.0",
    "bcrypt>=4.3.0",
    "passlib[bcrypt]>=1.7.4",
    "tqdm>=4.67.1",
    "langchain>=1.0.5",
    "langchain-chroma>=1.0.0",
    "langchain-perplexity>=1.0.0",
    "langchain-huggingface>=1.0.1",
    "langchain-community>=0.4.1",
]
